packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - unrs-resolver

catalog:
  typescript: ^6.0.3
  zod: ^4.4.3
  '@types/node': ^24.13.3

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  unrs-resolver: true
