import type { KnowledgeApplicability } from './knowledge-policy';

export const STANDARD6P_KNOWLEDGE_VERSION = 'standard6p-reviewed-v1';
const tactic = (
  id: string,
  role: string,
  scenario: string,
  actionTypes: string[],
  allFacts: KnowledgeApplicability['allFacts'],
  trigger: string,
  action: string,
) => ({
  id,
  role,
  scenario,
  trigger,
  action,
  applicability: { reviewed: true, rulesets: ['standard6p'], actionTypes, allFacts },
});

/** 与 standard6p 实际能力一致的战术；不含其他板子的机制。 */
export const STANDARD6P_TACTICS = [
  tactic(
    'seer-first-check',
    'seer',
    'night_action',
    ['seer_check'],
    ['first_night'],
    '预言家首夜没有本局公开发言信息时选择查验目标。',
    '首夜各未知身份的验人命中率没有可靠差异。可优先定义后续难以从公开行为判断的玩家，但不要把历史风格当成当前身份，也不要编造首验依据。',
  ),
  tactic(
    'seer-information',
    'seer',
    'night_action',
    ['seer_check'],
    ['public_discussion'],
    '已有公开发言，需要选择下一次查验目标。',
    '优先选择结果能区分多个仍成立狼坑的未知玩家；若两狼已经由自己的可靠查验和对跳关系锁定，不要再假设第三只狼。只选存活、未查验的合法目标，说明结果分别如何改变后续判断。',
  ),
  tactic(
    'seer-report',
    'seer',
    'day_speech',
    ['speech'],
    ['has_check'],
    '预言家在公开发言中拥有查验信息。',
    '清楚报出自己的身份、查验目标和结果，再说明与当前公开声明的冲突及今天建议投谁。本局没有警徽，不安排警徽流；不能把自己的查验和别人的自称混为一谈。',
  ),
  tactic(
    'seer-vote',
    'seer',
    'vote',
    ['vote'],
    ['has_wolf_check'],
    '预言家已经亲自查验出狼人，进入放逐投票。',
    '优先处理仍存活的亲验狼人。若查杀已出局，结合对跳及公开票型推断剩余一狼；其他人报的金水不是自己的查验，不能据此排除尚未证实的玩家。',
  ),
  tactic(
    'witch-save',
    'witch',
    'night_action',
    ['witch_save'],
    ['first_night', 'antidote_unused'],
    '女巫首夜有解药且系统提供了可救刀口。',
    '六人局轮次紧，首夜救人通常能保留更多好人行动机会。救下的玩家只说明曾被刀，不保证是好人；记录实际救人对象，之后不能把银水当成铁金水。',
  ),
  tactic(
    'witch-poison-uncertain',
    'witch',
    'night_action',
    ['witch_poison'],
    ['public_discussion', 'poison_unused'],
    '女巫有毒药且已经听过本局公开讨论。',
    '用当时可见的可靠证据比较毒人和留毒的收益，并考虑自己能否活到下次行动。对跳者给自己发假查杀是强证据；单纯发言强势或历史印象不足以确认身份。必要时承认不确定，不能机械要求每晚用毒。',
  ),
  tactic(
    'witch-last-poison',
    'witch',
    'night_action',
    ['witch_poison'],
    ['self_targeted', 'poison_unused'],
    '女巫看到自己被刀，无法自救且仍有毒药。',
    '比较临死用毒与带走毒药的阵营收益，按本局已有证据选择目标。完全没有信息时承认是盲毒，不能声称某种性格必为狼人，也不能以实际毒中结果证明选择正确。',
  ),
  tactic(
    'villager-vote',
    'villager',
    'vote',
    ['vote'],
    ['public_discussion'],
    '平民听过公开发言后需要投票。',
    '区分已确认事实、自称身份和推测，核对各预言家声明与实际票型；选择更能解释公开证据的狼坑。明确自己的最终目标并避免无依据分票，发言气势和顺序本身不能证明真伪。',
  ),
  tactic(
    'villager-speech',
    'villager',
    'day_speech',
    ['speech'],
    [],
    '平民需要在白天表达自己的判断。',
    '指出具体声明之间的矛盾和仍缺少的证据，说明自己倾向投谁以及什么新信息会改变判断。没有夜间身份信息就不要编造刀口、查验或用药事实。',
  ),
  tactic(
    'wolf-kill',
    'werewolf',
    'night_action',
    ['wolf_kill', 'wolf_proposal'],
    [],
    '狼队在夜间决定刀人。',
    '结合公开身份声明和剩余人数比较刀神、刀民及次日票型收益，优先推进本局实际胜利条件。首夜身份未知时不要把玩家风格当作神职证明；自刀必须有明确收益，不为制造故事而牺牲轮次。',
  ),
  tactic(
    'wolf-vote',
    'werewolf',
    'vote',
    ['vote'],
    ['public_discussion'],
    '狼人进入放逐投票，需要协调阵营收益。',
    '比较跟队友冲票、倒钩和分票对当前可执行胜利路径的影响。避免嘴上明确归票而实际投到无关目标；牺牲队友需有存活或后续获胜收益，不能仅为显得像好人。',
  ),
  tactic(
    'wolf-explode',
    'werewolf',
    'night_action',
    ['wolf_explode'],
    [],
    '天亮后狼人可以选择自爆或继续白天。',
    '自爆会立即牺牲自己，换取跳过本次白天。若自己是最后一狼，自爆会直接令好人获胜；有队友时也应比较继续发言投票和自爆后的狼刀收益，不能把自爆当作免费跳过白天。',
  ),
  tactic(
    'wolf-speech',
    'werewolf',
    'day_speech',
    ['speech'],
    [],
    '狼人需要向全场公开发言。',
    '公开论证只使用好人可以获知的信息，不能泄漏真实队友或未公开刀口。提前核对自己宣称的查验、站边和投票是否一致，用一致的可见证据推动目标。',
  ),
  tactic(
    'last-words',
    'any',
    'last_words',
    ['speech'],
    [],
    '出局玩家可以留下遗言。',
    '将能合法公开的身份信息、实际行动与仍不确定的推断分开表述。好人交代可靠线索及后续判断条件，狼人注意伪装的一致性；不使用死后或其他玩家私有信息。',
  ),
];
